### ISSUE TITLE
Route-aware <Link /> tags

### ISSUE THREAD

**Issue by matthewmueller** [matthewmueller/next-route#1]
Instead of:

```js
<Link href={`/author?author=${slug}`} as={`/${slug}`}>
```

Run it through the routes, so href will get resolve and we only need href:

```js
<Link href={`/${slug}`}>
```

**Comment by sedubois** [comment]
Agreed, e.g https://github.com/fridays/next-routes does this. But if that were supported, I'd be interested to try your package because it seems to support wildcards at root level well (e.g `"/:post"`).

**Comment by matthewmueller** [comment]
Supported in 2.0.0 👍
